### ISSUE TITLE
return *localVarResponse.Data, localVarHttpResponse.Header, err.   panic

### ISSUE THREAD

**Issue by hwzp99** [TencentAd/marketing-api-go-sdk#22]
github.com/tencentad/marketing-api-go-sdk v1.7.6

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x10a8c2b]

goroutine 244 [running]:
github.com/tencentad/marketing-api-go-sdk/pkg/api.(*AdcreativesApiService).Get(0xc0003ce490, 0x2505680, 0xc000486780, 0x81b6bd, 0xc000114720, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/tencentad/marketing-api-go-sdk@v1.7.6/pkg/api/api_adcreatives.go:338 +0xbfb

**Comment by dingdaofeng** [comment]
> github.com/tencentad/marketing-api-go-sdk v1.7.6
> 
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x10a8c2b]
> 
> goroutine 244 [running]:
> github.com/tencentad/marketing-api-go-sdk/pkg/api.(*AdcreativesApiService).Get(0xc0003ce490, 0x2505680, 0xc000486780, 0x81b6bd, 0xc000114720, 0x0, 0x0, 0x0, 0x0, 0x0)
> /root/go/pkg/mod/github.com/tencentad/marketing-api-go-sdk@v1.7.6/pkg/api/api_adcreatives.go:338 +0xbfb

这是偶发错误么？正常调用时没有复现，有出错时的请求和应答么？

**Comment by Shinku-Chen** [comment]
偶发现象
差不多2~3天偶尔出现一次     
每小时一次的频率

**Comment by hwzp99** [comment]
> > github.com/tencentad/marketing-api-go-sdk v1.7.6
> > panic: runtime error: invalid memory address or nil pointer dereference
> > [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x10a8c2b]
> > goroutine 244 [running]:
> > github.com/tencentad/marketing-api-go-sdk/pkg/api.(*AdcreativesApiService).Get(0xc0003ce490, 0x2505680, 0xc000486780, 0x81b6bd, 0xc000114720, 0x0, 0x0, 0x0, 0x0, 0x0)
> > /root/go/pkg/mod/github.com/tencentad/marketing-api-go-sdk@v1.7.6/pkg/api/api_adcreatives.go:338 +0xbfb
> 
> 这是偶发错误么？正常调用时没有复现，有出错时的请求和应答么？

偶发，但是出现概率还是比较大的
没有出错时的请求和应答

**Comment by hwzp99** [comment]
偶然发现环境有此打印，这个panic是不是和这个类似?
{"Op":"dial","Net":"tcp","Source":null,"Addr":{"IP":"2402:4e00:8020:101::2:296","Port":443,"Zone":""},"Err":{"Syscall":"connect","Err":99}}
 call tencent adcreative_templates/get failed, err:Get "https://api.e.qq.com/v1.1/adcreative_templates/get?access_token=8247406d75db80ca8f98b474cad223e6&account_id=17837208&fields=%5B%22adcreative_template_id%22%2C%22adcreative_template_appellation%22%5D&filtering=%5B%7B%22field%22%3A%22promoted_object_type%22%2C%22operator%22%3A%22EQUALS%22%2C%22values%22%3A%5B%22PROMOTED_OBJECT_TYPE_APP_ANDROID%22%5D%7D%2C%7B%22field%22%3A%22site_set%22%2C%22operator%22%3A%22EQUALS%22%2C%22values%22%3A%5B%22SITE_SET_TENCENT_NEWS%22%5D%7D%2C%7B%22field%22%3A%22is_dynamic_creative%22%2C%22operator%22%3A%22EQUALS%22%2C%22values%22%3A%5B%220%22%5D%7D%5D&nonce=260cc4d68ac14dfd&page=1&page_size=100&timestamp=1639201533": http: RoundTripper implementation (*ads.SDKClient) returned a nil *Response with a nil error,

**Comment by Shinku-Chen** [comment]
你可以这样理解
并没有返回数据,结构体内的数据就是nil,但判定数据的时候是获取这个nil结构体下面的属性 这样就是panic了

**Comment by hwzp99** [comment]
@KylinHuang7 官方的sdk，没有返回数据的时候也不应该出现panic

**Comment by dingdaofeng** [comment]
> @KylinHuang7 官方的sdk，没有返回数据的时候也不应该出现panic

会增加nil panic的检查
